id = "haml"
name = "Haml"
version = "0.4.0"
schema_version = 1
authors = ["David Cornu <me@davidcornu.com>"]
description = "Haml template support"
repository = "https://github.com/davidcornu/zed-haml"
snippets = "./snippets/snippets.json"

[grammars.haml]
repository = "https://github.com/vitallium/tree-sitter-haml"
rev = "ef9d881dddfd8d2d3b07b3e4f74353142476edc1"
