id = "haml"
name = "Haml"
version = "0.1.1"
schema_version = 1
authors = ["David Cornu <me@davidcornu.com>"]
description = "Haml template support"
repository = "https://github.com/davidcornu/zed-haml"

[grammars.haml]
repository = "https://github.com/vitallium/tree-sitter-haml"
rev = "a2af65572be29bb79ef00dd787776b57a82ab16d"
