id = "haml"
name = "Haml"
version = "0.1.3"
schema_version = 1
authors = ["David Cornu <me@davidcornu.com>"]
description = "Haml template support"
repository = "https://github.com/davidcornu/zed-haml"

[grammars.haml]
repository = "https://github.com/vitallium/tree-sitter-haml"
rev = "3e5bdaef84a7a65bd8e2f8a6f69120b53dac1e94"
