id = "haml"
name = "Haml"
version = "0.0.4"
schema_version = 1
authors = ["David Cornu <me@davidcornu.com>"]
description = "Haml template support"
repository = "https://github.com/davidcornu/zed-haml"

[grammars.haml]
repository = "https://github.com/vitallium/tree-sitter-haml"
rev = "1d3766b84005009febd5471be561b876f1db503d"
